routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses'=>'Admin\\TvChannelController@web','as'=>'web.welcome']);
//Route::get('info', function () {
//    phpinfo();
//});
Auth::routes();
Route::get('/movie',['uses'=>'FrontMovieController@search','as'=>'web.movie']);
Route::get('/movie/{id}/{name}',['uses'=>'FrontMovieController@show','as'=>'web.movie.show']);
Route::get('/movie/{id}/download/{name}',['uses'=>'FrontMovieController@download','as'=>'web.movie.download']);
Route::get('/movie/search',['uses'=>'FrontMovieController@search','as'=>'web.movie.search']);
Route::get('/movie/recent',['uses'=>'FrontMovieController@recentUpload','as'=>'web.movie.recent']);

Route::get('/software',['uses'=>'FrontSoftwareController@index','as'=>'web.software.index']);
Route::get('/software/{id}/{name}',['uses'=>'FrontSoftwareController@download','as'=>'web.software.show']);
Route::get('/software/download/{id}/{name}',['uses'=>'FrontSoftwareController@download','as'=>'web.software.download']);

Route::get('/game',['uses'=>'FrontGameController@index','as'=>'web.game.index']);
Route::get('/game/{id}/{name}',['uses'=>'FrontGameController@show','as'=>'web.game.show']);
Route::get('/game/download/{id}/{name}',['uses'=>'FrontGameController@download','as'=>'web.game.download']);

Route::get('/tv-series',['uses'=>'FrontTvSeriesController@index','as'=>'web.series.index']);
Route::get('/tv-series/{id}/{name}',['uses'=>'FrontTvSeriesController@show','as'=>'web.series.show']);
Route::get('/tv-series/download/{id}/{name}/{episode?}',['uses'=>'FrontTvSeriesController@download','as'=>'web.series.download']);
Route::get('/tv-series/watch/{id}/season/{name}/episode/{episode}',['uses'=>'FrontTvSeriesController@watch','as'=>'web.series.watch']);
Route::get('/tv-series/watch/{id}/episode/{episode}',['uses'=>'FrontTvSeriesController@episodeWatch','as'=>'web.series.episode.watch']);
Route::get('/live-tv',['uses'=>'Admin\\TvChannelController@web','as'=>'web.live-tv']);
Route::get('/live-tv/{id}/{name}',['uses'=>'Admin\\TvChannelController@watch','as'=>'web.tv-channel.watch']);
Route::get('/home', 'HomeController@index')->name('home')->middleware(['web','auth']);
Route::namespace('Admin')->middleware(['web', 'auth'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('dashboard', 'DashboardController@dashboard');
    Route::resource('movie-category', 'MovieCategoryController');
    Route::resource('genre', 'GenreController');
    Route::resource('movies', 'MovieController');
    Route::post('upload/movie', 'UploadController@upload');

    Route::resource('webslider', 'WebSliderController');

    Route::resource('softwarecategory', 'SoftwareCategoryController');
    Route::post('software/upload', 'SoftwareController@upload');
    Route::resource('software', 'SoftwareController');

    Route::post('game/upload', 'GameController@upload');
    Route::resource('gamecategory', 'GameCategoryController');
    Route::resource('gameplatform', 'GamePlatformController');
    Route::resource('gamepublisher', 'GamePublisherController');
    Route::resource('game', 'GameController');
    Route::resource('tvseriescategory', 'TvSeriesCategoryController');
    Route::resource('episode', 'EpisodeController');
    Route::post('tvseries/upload', 'TvSeriesController@upload');
    Route::get('tvseries/season/{id}', 'TvSeriesController@season');
    Route::get('/tvseries/{id}/delete/confirm','TvSeriesController@deleteConfirm');
    Route::resource('tvseries', 'TvSeriesController');

    Route::get('/tvseriesseason/{id}/delete/confirm','TvSeriesSeasonController@deleteConfirm');
    Route::resource('tvseriesseason', 'TvSeriesSeasonController');

    Route::resource('tvchannelcategory', 'TvChannelCategoryController');
    Route::resource('tvchannel', 'TvChannelController');

});

app/TvSeriesSeason.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TvSeriesSeason extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'tv_series_seasons';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['tv_sesries_id', 'name', 'status','release_date'];

    //use SoftDeletes;
    protected $dates = ['deleted_at'];

    public function tvSeries()
    {
        return $this->belongsTo(TvSeries::class,'tv_sesries_id','id');
    }

    public function episodes()
    {
        return $this->hasMany(Episode::class,'season_id','id');
    }

}

app/Http/Controllers/Admin/TvSeriesSeasonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\TvSeriesSeason;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Session;

class TvSeriesSeasonController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $tvseriesseason = TvSeriesSeason::all();

        return view('backEnd.tvseriesseason.index', compact('tvseriesseason'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('backEnd.tvseriesseason.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Requests\TvSeriesSeasonRequest $request)
    {


        $season = new TvSeriesSeason();
        $season->tv_sesries_id = $request->tv_sesries_id;
        $season->name = $request->name;
        $season->status = $request->status;
        $season->release_date = date_create_from_format('d/m/Y',$request->release_date)->format('Y-m-d');

        if($season->save())
        {
            flash('Successfully Save Season');
            return redirect('admin/tvseriesseason/'.$season->id);
        }else {
            flash('Fail! to Save Season');
            return redirect()->back()->withInput();
        }

        return redirect('admin/tvseriesseason');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tvseriesseason = TvSeriesSeason::findOrFail($id);

        return view('backEnd.tvseriesseason.show', compact('tvseriesseason'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tvseriesseason = TvSeriesSeason::findOrFail($id);

        return view('backEnd.tvseriesseason.edit', compact('tvseriesseason'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function update($id, Requests\TvSeriesSeasonRequest $request)
    {

        $season = TvSeriesSeason::findOrFail($id);
        $season->tv_sesries_id = $request->tv_sesries_id;
        $season->name = $request->name;
        $season->status = $request->status;
        $season->release_date = date_create_from_format('d/m/Y',$request->release_date)->format('Y-m-d');

        if($season->save())
        {
            flash('Successfully Update Season');
            return redirect('admin/tvseriesseason/'.$season->id);
        }else {
            flash('Fail! to Update Season');
            return redirect()->back()->withInput();
        }

        return redirect('admin/tvseriesseason');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tvseriesseason = TvSeriesSeason::findOrFail($id);

        $deleteUrl = link_to('admin/tvseriesseason/'.$id.'/delete/confirm', $title = 'Confirm', $attributes = ['class'=>'btn btn-warning btn-xs']);
        flash()->overlay(" This Season may have episodes. By Deleteing, you will loose all episode too.</br>". $deleteUrl, 'Confirm Delete');
        return redirect()->back();

    }

    public function deleteConfirm($id)
    {
        $tvseriesseason = TvSeriesSeason::findOrFail($id);

        foreach ($tvseriesseason->episodes as $episode)
        {
            @Storage::disk('public')->delete('tv-series/'.$episode->file_name);
            $episode->delete();
        }

        if($tvseriesseason->delete())
        {
            flash('Successfuly delete Season')->success();
        }else {
            flash('Fail to delete Season')->error();
        }
        return redirect()->back();
    }

}

resources/views/backEnd/tvseriesseason/create.blade.php
@extends('backLayout.app')
@section('title')
Create new Tv Series Season
@stop
@section('style')
    <link rel="stylesheet" href="{{ URL::asset('/backend/vendors/select2/dist/css/select2.min.css') }}">
@endsection

@section('content')

    <h1>Create New Tv Series Season</h1>
    <hr/>

    {!! Form::open(['url' => 'admin/tvseriesseason', 'class' => 'form-horizontal']) !!}

            <div class="form-group {{ $errors->has('tv_sesries_id') ? 'has-error' : ''}}">
                {!! Form::label('tv_sesries_id', 'Tv Sesries Id: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::select('tv_sesries_id',tvSeriesDropDownForSeason(), null, ['class' => 'form-control', 'required' => 'required']) !!}
                    {!! $errors->first('tv_sesries_id', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                {!! Form::label('name', 'Name: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('release_date') ? 'has-error' : ''}}">
                {!! Form::label('release_date', 'Release Date: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::text('release_date', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    {!! $errors->first('release_date', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('status') ? 'has-error' : ''}}">
                {!! Form::label('status', 'Status: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                                <div class="checkbox">
                <label>{!! Form::radio('status', '1',true) !!} Publish</label>
            </div>
            <div class="checkbox">
                <label>{!! Form::radio('status', '0') !!} Unpublish</label>
            </div>
                    {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
                </div>
            </div>


    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
            {!! Form::submit('Create', ['class' => 'btn btn-primary form-control']) !!}
        </div>
    </div>
    {!! Form::close() !!}



@endsection



@section('scripts')
    <script src="{{ URL::asset('/backend/vendors/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ URL::asset('/backend/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>



    <script>
        $(document).ready(function() {
            $('#tv_sesries_id').select2({
                placeholder: 'Select Series'
            });
            $("#release_date").inputmask("date", {
                    //placeholder: "yyyy-mm-dd",
                    insertMode: false,
                    showMaskOnHover: true,
                    //hourFormat: 12
                }
            );

        });


    </script>
@endsection

resources/views/backEnd/tvseriesseason/edit.blade.php
@extends('backLayout.app')
@section('title')
Edit Tv Series Season
@stop
@section('style')
    <link rel="stylesheet" href="{{ URL::asset('/backend/vendors/select2/dist/css/select2.min.css') }}">
@endsection

@section('content')

    <h1>Edit Tv Series Season</h1>
    <hr/>

    {!! Form::model($tvseriesseason, [
        'method' => 'PATCH',
        'url' => ['admin/tvseriesseason', $tvseriesseason->id],
        'class' => 'form-horizontal'
    ]) !!}


    <div class="form-group {{ $errors->has('tv_sesries_id') ? 'has-error' : ''}}">
        {!! Form::label('tv_sesries_id', 'Tv Sesries Id: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::select('tv_sesries_id',tvSeriesDropDownForSeason(), null, ['class' => 'form-control', 'required' => 'required']) !!}
            {!! $errors->first('tv_sesries_id', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
        {!! Form::label('name', 'Name: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('release_date') ? 'has-error' : ''}}">
        {!! Form::label('release_date', 'Release Date: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            {!! Form::text('release_date', null, ['class' => 'form-control', 'required' => 'required']) !!}
            {!! $errors->first('release_date', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="form-group {{ $errors->has('status') ? 'has-error' : ''}}">
        {!! Form::label('status', 'Status: ', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
            <div class="checkbox">
                <label>{!! Form::radio('status', '1',true) !!} Publish</label>
            </div>
            <div class="checkbox">
                <label>{!! Form::radio('status', '0') !!} Unpublish</label>
            </div>
            {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
            {!! Form::submit('Update', ['class' => 'btn btn-primary form-control']) !!}
        </div>
    </div>
    {!! Form::close() !!}



@endsection



@section('scripts')
    <script src="{{ URL::asset('/backend/vendors/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ URL::asset('/backend/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>



    <script>
        $(document).ready(function() {
            $('#tv_sesries_id').select2({
                placeholder: 'Select Series'
            });
            $("#release_date").inputmask("date", {
                    //placeholder: "yyyy-mm-dd",
                    insertMode: false,
                    showMaskOnHover: true,
                    //hourFormat: 12
                }
            );

        });


    </script>
@endsection

resources/views/backEnd/tvseriesseason/index.blade.php
@extends('backLayout.app')
@section('title')
    Tv Series Season
@stop

@section('content')

    <h1>Tv Series Season <a href="{{ url('admin/tvseriesseason/create') }}" class="btn btn-primary pull-right btn-sm">Add New Tv Series Season</a></h1>
    <div class="table table-responsive">
        <table class="table table-bordered table-striped table-hover" id="tbladmin">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Tv Series</th>
                    <th>Release Date</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            @foreach($tvseriesseason as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->tvSeries->name }}</td>
                    <td>{{ $item->release_date }}</td>
                    <td>{{ activeStatus($item->status) }}</td>
                    <td>
                        <a href="{{ url('admin/tvseriesseason/' . $item->id ) }}" class="btn btn-success btn-xs">View</a>
                        <a href="{{ url('admin/tvseriesseason/' . $item->id . '/edit') }}" class="btn btn-primary btn-xs">Update</a> 
                        {!! Form::open([
                            'method'=>'DELETE',
                            'url' => ['admin/tvseriesseason', $item->id],
                            'style' => 'display:inline'
                        ]) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                        {!! Form::close() !!}

                        <a class="btn btn-info btn-xs" href="{{ route('admin.episode.index',['season'=>$item->id]) }}"> View Episode</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@endsection

@section('scripts')
<script type="text/javascript">
    $(document).ready(function(){
        $('#tbladmin').DataTable({

        });
    });
</script>
@endsection

resources/views/backEnd/tvseriesseason/show.blade.php
@extends('backLayout.app')
@section('title')
    Tv Series Season
@stop

@section('content')

    <h1>Tv Series Season
        <a class="btn btn-default" href="{{ url('admin/tvseriesseason') }}">All Seasons </a>
        <a class="btn btn-warning" href="{{ url('admin/tvseriesseason'.$tvseriesseason->id.'/edit') }}"> Edit Season</a>
        <a class="btn btn-info" href="{{ route('admin.episode.index',['season'=>$tvseriesseason->id]) }}"> View Episodes</a>
    </h1>
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">

            <tbody>
            <tr>
                <th>Name</th>
                <th>{{ $tvseriesseason->name }}</th>
            </tr>
            <tr>
                <th>Tv Series</th>
                <th>{{ $tvseriesseason->tvSeries->name }}</th>
            </tr>
            <tr>
                <th>Release Date</th>
                <th>{{ $tvseriesseason->release_date }}</th>
            </tr>
            <tr>
                <th>Status</th>
                <th>{{ activeStatus($tvseriesseason->status) }}</th>
            </tr>
            <tr>
                <th>Episodes</th>
                <th>
                    Total Episodes {{ $tvseriesseason->episodes()->count() }}

                </th>
            </tr>
            </tbody>    
        </table>
    </div>

@endsection