routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses'=>'Admin\\TvChannelController@web','as'=>'web.welcome']);
//Route::get('info', function () {
//    phpinfo();
//});
Auth::routes();
Route::get('/movie',['uses'=>'FrontMovieController@search','as'=>'web.movie']);
Route::get('/movie/{id}/{name}',['uses'=>'FrontMovieController@show','as'=>'web.movie.show']);
Route::get('/movie/{id}/download/{name}',['uses'=>'FrontMovieController@download','as'=>'web.movie.download']);
Route::get('/movie/search',['uses'=>'FrontMovieController@search','as'=>'web.movie.search']);
Route::get('/movie/recent',['uses'=>'FrontMovieController@recentUpload','as'=>'web.movie.recent']);

Route::get('/software',['uses'=>'FrontSoftwareController@index','as'=>'web.software.index']);
Route::get('/software/{id}/{name}',['uses'=>'FrontSoftwareController@download','as'=>'web.software.show']);
Route::get('/software/download/{id}/{name}',['uses'=>'FrontSoftwareController@download','as'=>'web.software.download']);

Route::get('/game',['uses'=>'FrontGameController@index','as'=>'web.game.index']);
Route::get('/game/{id}/{name}',['uses'=>'FrontGameController@show','as'=>'web.game.show']);
Route::get('/game/download/{id}/{name}',['uses'=>'FrontGameController@download','as'=>'web.game.download']);

Route::get('/tv-series',['uses'=>'FrontTvSeriesController@index','as'=>'web.series.index']);
Route::get('/tv-series/{id}/{name}',['uses'=>'FrontTvSeriesController@show','as'=>'web.series.show']);
Route::get('/tv-series/download/{id}/{name}/{episode?}',['uses'=>'FrontTvSeriesController@download','as'=>'web.series.download']);
Route::get('/tv-series/watch/{id}/season/{name}/episode/{episode}',['uses'=>'FrontTvSeriesController@watch','as'=>'web.series.watch']);
Route::get('/tv-series/watch/{id}/episode/{episode}',['uses'=>'FrontTvSeriesController@episodeWatch','as'=>'web.series.episode.watch']);
Route::get('/live-tv',['uses'=>'Admin\\TvChannelController@web','as'=>'web.live-tv']);
Route::get('/live-tv/{id}/{name}',['uses'=>'Admin\\TvChannelController@watch','as'=>'web.tv-channel.watch']);
Route::get('/home', 'HomeController@index')->name('home')->middleware(['web','auth']);
Route::namespace('Admin')->middleware(['web', 'auth'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('dashboard', 'DashboardController@dashboard');
    Route::resource('movie-category', 'MovieCategoryController');
    Route::resource('genre', 'GenreController');
    Route::resource('movies', 'MovieController');
    Route::post('upload/movie', 'UploadController@upload');

    Route::resource('webslider', 'WebSliderController');

    Route::resource('softwarecategory', 'SoftwareCategoryController');
    Route::post('software/upload', 'SoftwareController@upload');
    Route::resource('software', 'SoftwareController');

    Route::post('game/upload', 'GameController@upload');
    Route::resource('gamecategory', 'GameCategoryController');
    Route::resource('gameplatform', 'GamePlatformController');
    Route::resource('gamepublisher', 'GamePublisherController');
    Route::resource('game', 'GameController');
    Route::resource('tvseriescategory', 'TvSeriesCategoryController');
    Route::resource('episode', 'EpisodeController');
    Route::post('tvseries/upload', 'TvSeriesController@upload');
    Route::get('tvseries/season/{id}', 'TvSeriesController@season');
    Route::get('/tvseries/{id}/delete/confirm','TvSeriesController@deleteConfirm');
    Route::resource('tvseries', 'TvSeriesController');

    Route::get('/tvseriesseason/{id}/delete/confirm','TvSeriesSeasonController@deleteConfirm');
    Route::resource('tvseriesseason', 'TvSeriesSeasonController');

    Route::resource('tvchannelcategory', 'TvChannelCategoryController');
    Route::resource('tvchannel', 'TvChannelController');

});

app/Http/Controllers/Admin/TvSeriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Http\Requests\TvSeriesRequest;
use App\TvSeries;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Session;

use Illuminate\Http\UploadedFile;
use Pion\Laravel\ChunkUpload\Exceptions\UploadMissingFileException;
use Pion\Laravel\ChunkUpload\Handler\AbstractHandler;
use Pion\Laravel\ChunkUpload\Handler\HandlerFactory;
use Pion\Laravel\ChunkUpload\Receiver\FileReceiver;

class TvSeriesController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $tvseries = TvSeries::all();

        return view('backEnd.tvseries.index', compact('tvseries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('backEnd.tvseries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(TvSeriesRequest $request)
    {
      // return $request->all();
        $path = '';
        if ($request->hasFile('image')) {
            $imageName = str_replace(" ",'_',$request->name).'_'.time().'.'.$request->image->extension();
            $path = $request->image->storeAs('tv-series/images', $imageName, 'public');
        }

        $tvSeries = new TvSeries();
        $tvSeries->category_id = $request->category_id;
        $tvSeries->name = $request->name;
        $tvSeries->description = $request->description;
        $tvSeries->release_date = date_create_from_format('d/m/Y',$request->release_date)->format('Y-m-d');
        $tvSeries->status = $request->status;
        $tvSeries->image = $path;
        $tvSeries->file_name = ($request->file_present) ? $request->file_name : null;
        $tvSeries->has_episode = $request->has_episode;
        $tvSeries->has_season = $request->has_season;


        if($tvSeries->save())
        {
            $tvSeries->genres()->attach($request->genre_id);
            flash('Successfully Save Series');
            return redirect('admin/tvseries/'.$tvSeries->id);
        }else {
            flash('Fail! to Save Series');
            return redirect()->back()->withInput();
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tvseries = TvSeries::findOrFail($id);

        return view('backEnd.tvseries.show', compact('tvseries'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tvseries = TvSeries::findOrFail($id);

        return view('backEnd.tvseries.edit', compact('tvseries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function update($id, TvSeriesRequest $request)
    {
        $tvSeries = TvSeries::findOrFail($id);
        $path = '';
        if ($request->hasFile('image')) {
            $imageName = str_replace(" ",'_',$request->name).'_'.time().'.'.$request->image->extension();
            $path = $request->image->storeAs('tv-series/images', $imageName, 'public');
        } else {
            $path = $tvSeries->image;
        }


        $tvSeries->category_id = $request->category_id;
        $tvSeries->name = $request->name;
        $tvSeries->description = $request->description;
        $tvSeries->release_date = date_create_from_format('d/m/Y',$request->release_date)->format('Y-m-d');
        $tvSeries->status = $request->status;
        $tvSeries->image = $path;
        $tvSeries->file_name = ($request->file_present) ? $request->file_name : $tvSeries->file_name;
        $tvSeries->has_episode = $request->has_episode;
        $tvSeries->has_season = $request->has_season;
        if($tvSeries->save())
        {
            $tvSeries->genres()->sync($request->genre_id);
            flash('Successfully Update Series');
            return redirect('admin/tvseries/'.$tvSeries->id);
        }else {
            flash('Fail! to Update Series');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tvseries = TvSeries::findOrFail($id);

        //$tvseries->delete();
        if($tvseries->has_episode)
        {
            $deleteUrl = link_to('admin/tvseries/'.$id.'/delete/confirm', $title = 'Confirm', $attributes = ['class'=>'btn btn-warning btn-xs']);
            flash()->overlay("This TV Series has episode. Please confirm to delete all Episode too. </br>". $deleteUrl, 'Modal Title');
            return redirect()->back();
        }

        if($tvseries->has_season)
        {
            $deleteUrl = link_to('admin/tvseries/'.$id.'/delete/confirm', $title = 'Confirm', $attributes = ['class'=>'btn btn-warning btn-xs']);
            flash()->overlay("This TV Series has season. Please confirm to delete all Season too. </br>". $deleteUrl, 'Modal Title');
            return redirect()->back();
        }

        $tvseries->genres()->detach();
        if($tvseries->delete())
        {
            flash('Successfuly delete tv series')->success();
        }else {
            flash('Fail to delete TV Series')->error();
        }
        return redirect()->back();
    }

    public function deleteConfirm($id)
    {
        $tvseries = TvSeries::findOrFail($id);

        if($tvseries->has_episode)
        {
            foreach ($tvseries->episodes as $episode)
            {
                @Storage::disk('public')->delete('tv-series/'.$episode->file_name);
                $episode->delete();
            }

        }

        if($tvseries->has_seasons)
        {
            foreach ($tvseries->seasons as $season)
            {
                foreach ($season->episodes as $episode)
                {
                    @Storage::disk('public')->delete('tv-series/'.$episode->file_name);
                    $episode->delete();
                }
                $season->delete();
            }

        }

        $tvseries->genres()->detach();
        if($tvseries->delete())
        {
            flash('Successfuly delete tv series')->success();
        }else {
            flash('Fail to delete TV Series')->error();
        }
        return redirect()->back();
    }


    /**
     * Handles the file upload
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     *
     * @throws UploadMissingFileException
     * @throws \Pion\Laravel\ChunkUpload\Exceptions\UploadFailedException
     */
    public function upload(Request $request) {

        $receiver = new FileReceiver("file", $request, HandlerFactory::classFromRequest($request));

        if ($receiver->isUploaded() === false) {
            throw new UploadMissingFileException();
        }

        $save = $receiver->receive();

        if ($save->isFinished()) {

            return $this->saveFile($save->getFile());
        }


        $handler = $save->handler();
        return response()->json([
            "done" => $handler->getPercentageDone(),
            'status' => true
        ]);
    }

    /**
     * Saves the file
     *
     * @param UploadedFile $file
     *
     * @return \Illuminate\Http\JsonResponse
     */
    protected function saveFile(UploadedFile $file)
    {
        $fileName = $this->createFilename($file);
        // Group files by mime type
        $mime = str_replace('/', '-', $file->getMimeType());
        // Group files by the date (week
        //$dateFolder = date("Y-m-W");
        // Build the file path
        $filePath = "public/tv-series";
        $finalPath = storage_path("app/".$filePath);
        // move the file name
        $file->move($finalPath, $fileName);
        return response()->json([
            'path' => $filePath,
            'name' => $fileName,
            'mime_type' => $mime
        ]);
    }
    /**
     * Create unique filename for uploaded file
     * @param UploadedFile $file
     * @return string
     */
    protected function createFilename(UploadedFile $file)
    {
        $extension = $file->getClientOriginalExtension();
        $filename = str_replace(".".$extension, "", $file->getClientOriginalName()); // Filename without extension
        $filename = str_replace(" ", "_", $filename);
        // Add timestamp to name of the file
        $filename .= "_" . time() . "." . $extension;
        return $filename;
    }


    public function season($id)
    {
        $tvSeries = TvSeries::findOrFail($id);
        $response = [
            'has_season'=>$tvSeries->has_season,
            'seasons' => tvSeriesSeasonDropDown($id)
        ];
        return response()->json($response);
    }

}

resources/views/backEnd/tvseries/_file_browse.blade.php
<div id="fileBrowserDiv" class="form-group hidden">
    {!! Form::label('File', 'Select Movie File: ', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-6">
        <span class="btn btn-success" id="browseButton">Browse</span>
        <span class="btn btn-success hidden" id="browseUpload">Upload</span>
        <span class="btn btn-warning hidden" id="browsePause">Pause</span>
        <span class="btn btn-primary hidden" id="browseResume">Resume</span>
        <span class="btn btn-danger hidden" id="browseCancel">Cancel</span>

        <div class="progress hidden" id="progressDiv">
            <div class="progress-bar progress-bar-success" id="browseProgress" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em;">
                0%
            </div>
        </div>
    </div>

</div>

resources/views/backEnd/tvseries/create.blade.php
@extends('backLayout.app')
@section('title')
Create new Tv Series
@stop
@section('style')
    <link rel="stylesheet" href="{{ URL::asset('/backend/vendors/select2/dist/css/select2.min.css') }}">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
@endsection
@section('content')

    <h1>Create New Tv Series</h1>
    <hr/>

    {!! Form::open(['url' => 'admin/tvseries', 'class' => 'form-horizontal','files'=>true]) !!}
            @include('backEnd.tvseries._file_browse')
            {!! Form::hidden('file_present') !!}
            <div class="form-group {{ $errors->has('category_id') ? 'has-error' : ''}}">
                {!! Form::label('category_id', 'Category: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::select('category_id', tvSeriesCategoryDropdown(),null, ['class' => 'form-control', 'required' => 'required']) !!}
                    {!! $errors->first('category_id', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('genre_id') ? 'has-error' : ''}}">
                {!! Form::label('genre_id', 'Genre: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::select('genre_id[]', genreDropdown(), null, ['class' => 'form-control', 'required' => 'required','multiple'=>'multiple','id'=>'genre_id']) !!}
                    {!! $errors->first('genre_id', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                {!! Form::label('name', 'Name: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div id="fileNameDiv" class="form-group hidden {{ $errors->has('file_name') ? 'has-error' : ''}}">
                {!! Form::label('file_name', 'File Name: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::text('file_name', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('file_name', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('release_date') ? 'has-error' : ''}}">
                {!! Form::label('release_date', 'Release Date: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::text('release_date', null, ['class' => 'form-control', 'required' => 'required']) !!}
                    {!! $errors->first('release_date', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
                {!! Form::label('image', 'Image: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::file('image', ['class' => 'form-control', 'required' => 'required']) !!}
                    {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
                {!! Form::label('description', 'Description: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('has_season') ? 'has-error' : ''}}">
                {!! Form::label('has_season', 'Has Season: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    <div class="checkbox">
                        <label>{!! Form::radio('has_season', '1',true) !!} Yes</label>
                        <label>{!! Form::radio('has_season', '0') !!} No</label>
                    </div>
                    {!! $errors->first('has_season', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('has_episode') ? 'has-error' : ''}}">
                {!! Form::label('has_episode', 'Has Episode: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    <div class="checkbox">
                        <label>{!! Form::radio('has_episode', '1') !!} Yes</label>
                        <label>{!! Form::radio('has_episode', '0',true) !!} No</label>
                    </div>

                    {!! $errors->first('has_episode', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            <div class="form-group {{ $errors->has('status') ? 'has-error' : ''}}">
                {!! Form::label('status', 'Status: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    <div class="checkbox">
                        <label>{!! Form::radio('status', '1', true) !!} Publish</label>
                        <label>{!! Form::radio('status', '0') !!} Unpublish</label>
                    </div>

                    {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
                </div>
            </div>


    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
            {!! Form::submit('Create', ['class' => 'btn btn-primary form-control']) !!}
        </div>
    </div>
    {!! Form::close() !!}


@endsection


@section('scripts')
    <script src="{{ URL::asset('/backend/vendors/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ URL::asset('/backend/vendors/resumeable/resumeable.js') }}"></script>
    <script src="{{ URL::asset('/backend/js/tv-series.js') }}"></script>
    <script src="{{ URL::asset('/backend/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>

    <script>
        $(document).ready(function() {
            $('#genre_id').select2({
                placeholder: 'Select Genre'
            });


            $("#release_date").inputmask("date", {
                    //placeholder: "yyyy-mm-dd",
                    insertMode: false,
                    showMaskOnHover: true,
                    //hourFormat: 12
                }
            );

            $('#description').summernote();
            var has_episode = {{ old('has_episode',0) }};
            var has_season = {{old('has_season',1)}};
            setFileBrowser(has_episode, has_season);
            $('input:radio[name="has_episode"], input:radio[name="has_season"]').on('click',function(event){
                 has_episode = $('input:radio[name="has_episode"]:checked').val();
                 has_season = $('input:radio[name="has_season"]:checked').val();
                setFileBrowser(has_episode, has_season);
            });

        });

        function setFileBrowser(episode,seasson)
        {
            if(episode ==0 && seasson==0)
            {

                $('#fileNameDiv').removeClass('hidden');
                $('#fileBrowserDiv').removeClass('hidden');
                $('input[name="file_present"]').val(1);
            }else {

                $('#fileNameDiv').addClass('hidden');
                $('#fileBrowserDiv').addClass('hidden');
                $('input[name="file_present"]').removeAttr('value');
            }
        }
    </script>
@endsection

resources/views/backEnd/tvseries/index.blade.php
@extends('backLayout.app')
@section('title')
    Tv Series
@stop

@section('content')

    <h1>Tv Series <a href="{{ url('admin/tvseries/create') }}" class="btn btn-primary pull-right btn-sm">Add New Tv Series</a></h1>
    <div class="table table-responsive">
        <table class="table table-bordered table-striped table-hover" id="tbladmin">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Genre</th>
                    <th>Release date</th>
                    <th>Image</th>
                    <th>views</th>
                    <th>Download</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            @foreach($tvseries as $item)
                <tr>

                    <td>{{ $item->name }}</td>
                    <td>{{ $item->category->name }}</td>
                    <td>{{ tvSeriesGenresConcat($item) }}</td>
                    <td>{{ $item->release_date }}</td>
                    <td>
                        <img class=" img-thumbnail img-w-150" src="{{ asset('storage/'.$item->image) }}" alt="{{ $item->name }}">
                    </td>
                    <td>{{ $item->views }}</td>
                    <td>{{ $item->downloads }}</td>
                    <td>{{ activeStatus($item->status) }}</td>
                    <td>
                        <a href="{{ url('admin/tvseries/' . $item->id ) }}" class="btn btn-success btn-xs">View</a>
                        <a href="{{ url('admin/tvseries/' . $item->id . '/edit') }}" class="btn btn-primary btn-xs">Update</a> 
                        {!! Form::open([
                            'method'=>'DELETE',
                            'url' => ['admin/tvseries', $item->id],
                            'style' => 'display:inline'
                        ]) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs']) !!}
                        {!! Form::close() !!}
                        <a href="{{ url('admin/episode?').'tvseries='.$item->id }}" class="btn btn-success btn-xs">Episodes</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@endsection

@section('scripts')
<script type="text/javascript">
    $(document).ready(function(){
        $('#tbladmin').DataTable({

        });
    });
</script>
@endsection

resources/views/backEnd/tvseries/show.blade.php
@extends('backLayout.app')
@section('title')
    Tv Series
@stop

@section('content')

    <h1>Tv Series
        <a class="btn btn-default" href="{{ route('admin.tvseries.index') }}">Series List</a>
        <a class="btn btn-warning" href="{{ route('admin.tvseries.edit',['id'=>$tvseries->id]) }}">Edit</a>
    </h1>
    <div class="row">
        <div class="col-md-6">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover">

                    <tbody>
                    <tr>
                        <th>Name</th>
                        <th>{{ $tvseries->name }}</th>
                    </tr>
                    <tr>
                        <th>Category</th>
                        <th>{{ $tvseries->category->name }}</th>
                    </tr>
                    <tr>
                        <th>Genres</th>
                        <th>{{ tvSeriesGenresConcat($tvseries) }}</th>
                    </tr>
                    <tr>
                        <th>Release Date</th>
                        <th>{{ $tvseries->release_date }}</th>
                    </tr>
                    <tr>
                        <th>Views</th>
                        <th>{{ $tvseries->views }}</th>
                    </tr>
                    <tr>
                        <th>Downloads</th>
                        <th>{{ $tvseries->downloads }}</th>
                    </tr>
                    @if($tvseries->has_season)
                        <tr>
                            <th>Sessons</th>
                            <th>{{ tvSeriesSessonConcat($tvseries) }}</th>
                        </tr>

                    @endif
                    @if($tvseries->has_episode)
                        <tr>
                            <th>Total Episode</th>
                            <th>{{ $tvseries->episodes()->count() }}</th>
                        </tr>

                    @endif
                    <tr>
                        <th>Description</th>
                        <th>{!! $tvseries->description !!}</th>
                    </tr>

                    <tr>
                        <th>Status</th>
                        <th>{{ activeStatus($tvseries->status) }}</th>
                    </tr>
                    <tr>
                        <th>Image</th>
                        <th>
                            <img class=" img-thumbnail img-w-250" src="{{ asset('storage/'.$tvseries->image) }}" alt="{{ $tvseries->name }}">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-6">
            @if($tvseries->has_episode ==0 && $tvseries->has_season==0)
                <h3>Video </h3>
                <video style="max-width: 70%" controls src="{{ asset('storage/tv-series/'.$tvseries->file_name) }}"></video>
            @endif

        </div>
    </div>

@endsection